[package]
name = "minecraft"
version = "0.0.1"
edition = "2021"
description = "A universal Minecraft® downloader!"
license = "LGPL-3.0"
authors = ["D.A.Pelasgus"]
homepage = "https://minecraft.rs"

[dependencies]
minecraft-cli = "0.0.1"
